---
- name: Configure Waystream MS4K
  hosts: 10.20.128.108
  gather_facts: False

  vars:

    ansible_connection: network_cli
    ansible_network_os: asa

  tasks:
  - name: delete fw
    cli_command:
      command: delete flash:ibos-cma-7.5.17-ED-R.bz2

